# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'transformations'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'aws_eu_central'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
seeds:
  transformations:
    +snowflake_warehouse: "SMALL"
    raw:
      +schema: RAW
      +tags: "RAW"
      raw_market_region:
        +columns_types:
          country_market_region_id: INTEGER
          country_id: INTEGER
          market_region_name: VARCHAR
          sys_update_ts: TIMESTAMP
      raw_credits:
        +columns_types:
          person_id: VARCHAR
          id: VARCHAR
          name: VARCHAR
          character: VARCHAR
          role: VARCHAR
      raw_titles:
        +columns_types:
          id: VARCHAR
          title: VARCHAR
          type: VARCHAR
          description: VARCHAR
          release_year: VARCHAR
          age_certification: VARCHAR
          runtime: VARCHAR
          genres: VARCHAR
          production_countries: VARCHAR
          seasons: VARCHAR
          imdb_id: VARCHAR
          imdb_score: VARCHAR
          imdb_votes: VARCHAR
          tmdb_popularity: VARCHAR
          tmdb_score: VARCHAR

models:
  transformations:
    +snowflake_warehouse: "XSMALL"
    stg:
      +schema: STG
      +tags: "STG"
      +materialized: table
      +transient: true
